// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiUHTywICQYt10CDtRA4Q76ZiyL4CsuMM',
    appId: '1:461917017068:web:4a086ffacfae2238fd26c9',
    messagingSenderId: '461917017068',
    projectId: 'aarogyam-80aa2',
    authDomain: 'aarogyam-80aa2.firebaseapp.com',
    storageBucket: 'aarogyam-80aa2.appspot.com',
    measurementId: 'G-W9BSDTCWF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5KSYy-dfvGietMHrUz07bc8ZAgzJu-3g',
    appId: '1:461917017068:android:9bf4c40b9f7600fffd26c9',
    messagingSenderId: '461917017068',
    projectId: 'aarogyam-80aa2',
    storageBucket: 'aarogyam-80aa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5efW3muvhLkaXf9HiJbhhLHHZm8rXTC0',
    appId: '1:461917017068:ios:8ee2718ae5831ad7fd26c9',
    messagingSenderId: '461917017068',
    projectId: 'aarogyam-80aa2',
    storageBucket: 'aarogyam-80aa2.appspot.com',
    iosBundleId: 'com.example.adminPanelAarogyam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5efW3muvhLkaXf9HiJbhhLHHZm8rXTC0',
    appId: '1:461917017068:ios:5c8c9d7b1c962b39fd26c9',
    messagingSenderId: '461917017068',
    projectId: 'aarogyam-80aa2',
    storageBucket: 'aarogyam-80aa2.appspot.com',
    iosBundleId: 'com.example.adminPanelAarogyam.RunnerTests',
  );
}
